/gps/particle neutron

/gps/ene/type Lin
/gps/ene/min 1 MeV
/gps/ene/max 10.0 MeV
/gps/ene/gradient 0.0
/gps/ene/intercept 1.0

/gps/position 0 0 -1590 cm
/gps/direction 0 0 1
/gps/pos/shape Rectangle
/gps/pos/halfx 60 mm
/gps/pos/halfy 60 mm
/gps/pos/type Plane
/gps/ang/type iso
/gps/ang/maxtheta 0 deg
/gps/ang/mintheta 0 deg
/run/printProgress 100
/lumacam/sampleMaterial G4_Galactic
/lumacam/batchSize 100
/run/beamOn 2000